### ISSUE TITLE
On Ubuntu 16.04 / mono Mesen crash after first configuring

### ISSUE THREAD

**Issue by Schade8888** [SourMesen/Mesen#510]
Hi, I got a problem on launching Mesen. In the first install, I got the configuration screen and after that some files was created in the app's folder : 
```
GoogleDrive  libMesenCore.dll  MesenDB.txt  MesenDevLinux-0.9.7.3.exe
Resources    settings.xml

./GoogleDrive:
BouncyCastle.Crypto.dll		       Google.Apis.Auth.dll
Google.Apis.Auth.PlatformServices.dll  Google.Apis.Core.dll
Google.Apis.dll			       Google.Apis.Drive.v3.dll
Google.Apis.PlatformServices.dll       Newtonsoft.Json.dll
Zlib.Portable.dll

./Resources:
Font.24.spritefont  Font.64.spritefont	LICENSE.txt  PixelFont.ttf
```

But I got this error message (sorry I'm French) : 

![image](https://user-images.githubusercontent.com/43718429/46254857-2f26a380-c496-11e8-8742-3064048a6cfe.png)

this is the trace I got in the terminal  : 

```
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.XplatUIX11.XCreateFontCursor (intptr,System.Windows.Forms.CursorFontShape) <0xffffffff>
  at System.Windows.Forms.XplatUIX11.DefineStdCursor (System.Windows.Forms.StdCursor) <0x00057>
  at System.Windows.Forms.XplatUI.DefineStdCursor (System.Windows.Forms.StdCursor) <0x0001f>
  at System.Windows.Forms.Cursor..ctor (System.Windows.Forms.StdCursor) <0x0001b>
  at System.Windows.Forms.Cursors.get_Default () <0x00037>
  at System.Windows.Forms.ScrollBar..ctor () <0x005e3>
  at System.Windows.Forms.HScrollBar..ctor () <0x0000f>
  at System.Windows.Forms.ImplicitHScrollBar..ctor () <0x0000f>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ImplicitHScrollBar..ctor () <0xffffffff>
  at System.Windows.Forms.ScrollableControl.CreateScrollbars () <0x00033>
  at System.Windows.Forms.ScrollableControl..ctor () <0x0039b>
  at System.Windows.Forms.ContainerControl..ctor () <0x00027>
  at System.Windows.Forms.Form..ctor () <0x000e7>
  at System.Windows.Forms.MessageBox/MessageBoxForm..ctor (System.Windows.Forms.IWin32Window,string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon,bool) <0x0008f>
  at System.Windows.Forms.MessageBox/MessageBoxForm..ctor (System.Windows.Forms.IWin32Window,string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon) <0x00047>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.MessageBox/MessageBoxForm..ctor (System.Windows.Forms.IWin32Window,string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon) <0xffffffff>
  at System.Windows.Forms.MessageBox.Show (string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon) <0x0004b>
  at Mesen.GUI.Forms.MesenMsgBox.Show (string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon,string[]) <0x001ef>
  at Mesen.GUI.RuntimeChecker.TestDll () <0x0013b>
  at Mesen.GUI.Program.Main (string[]) <0x0066f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x49ff2f]
	mono() [0x4f390e]
	mono() [0x426c19]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7fa2f459a390]
	/lib64/ld-linux-x86-64.so.2(+0xc73c) [0x7fa2f4ec773c]
	/lib64/ld-linux-x86-64.so.2(+0x15851) [0x7fa2f4ed0851]
	/lib64/ld-linux-x86-64.so.2(+0x10564) [0x7fa2f4ecb564]
	/lib64/ld-linux-x86-64.so.2(+0x14da9) [0x7fa2f4ecfda9]
	/lib/x86_64-linux-gnu/libdl.so.2(+0xf09) [0x7fa2f47a6f09]
	/lib64/ld-linux-x86-64.so.2(+0x10564) [0x7fa2f4ecb564]
	/lib/x86_64-linux-gnu/libdl.so.2(+0x1571) [0x7fa2f47a7571]
	/lib/x86_64-linux-gnu/libdl.so.2(dlopen+0x31) [0x7fa2f47a6fa1]
	/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x1bdba) [0x7fa2e3ce1dba]
	/usr/lib/x86_64-linux-gnu/libX11.so.6(XCreateGlyphCursor+0x1bf) [0x7fa2e3ce22bf]
	/usr/lib/x86_64-linux-gnu/libX11.so.6(XCreateFontCursor+0x56) [0x7fa2e3ce2646]
	[0x400a6e86]

Debug info from gdb:

[New LWP 11348]
[New LWP 11349]
[New LWP 11350]
[New LWP 11351]
[New LWP 11352]
[New LWP 11353]
[New LWP 11354]
[New LWP 11355]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa2f4599f7b in __waitpid (pid=11356, stat_loc=0x7fa2f500710c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: Aucun fichier ou dossier de ce type.
  Id   Target Id         Frame 
* 1    Thread 0x7fa2f50a5780 (LWP 11347) "mono" 0x00007fa2f4599f7b in __waitpid (pid=11356, stat_loc=0x7fa2f500710c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7fa2f37ff700 (LWP 11348) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fa2f3ee1700 (LWP 11349) "Finalizer" 0x00007fa2f4598827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7fa2f4f46700 (LWP 11350) "mono" __clock_nanosleep (clock_id=<optimized out>, flags=1, req=0x7fa2f4f45db0, rem=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  5    Thread 0x7fa2f058b700 (LWP 11351) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fa2f038a700 (LWP 11352) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fa2d5e34700 (LWP 11353) "dconf worker" 0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84
  8    Thread 0x7fa2d5633700 (LWP 11354) "gmain" 0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84
  9    Thread 0x7fa2d4e32700 (LWP 11355) "gdbus" 0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84

Thread 9 (Thread 0x7fa2d4e32700 (LWP 11355)):
#0  0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fa2e316b38c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fa2e316b712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fa2daeb79d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fa2e3191c55 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa2f45906ba in start_thread (arg=0x7fa2d4e32700) at pthread_create.c:333
#6  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7fa2d5633700 (LWP 11354)):
#0  0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fa2e316b38c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fa2e316b49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fa2e316b4d9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fa2e3191c55 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa2f45906ba in start_thread (arg=0x7fa2d5633700) at pthread_create.c:333
#6  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7fa2d5e34700 (LWP 11353)):
#0  0x00007fa2f42ba74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fa2e316b38c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fa2e316b49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fa2d5e3c28d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fa2e3191c55 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa2f45906ba in start_thread (arg=0x7fa2d5e34700) at pthread_create.c:333
#6  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7fa2f038a700 (LWP 11352)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000058a192 in ?? ()
#2  0x0000000000587b2b in ?? ()
#3  0x0000000000629a8c in ?? ()
#4  0x00007fa2f45906ba in start_thread (arg=0x7fa2f038a700) at pthread_create.c:333
#5  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fa2f058b700 (LWP 11351)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000058a192 in ?? ()
#2  0x0000000000587b2b in ?? ()
#3  0x0000000000629a8c in ?? ()
#4  0x00007fa2f45906ba in start_thread (arg=0x7fa2f058b700) at pthread_create.c:333
#5  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fa2f4f46700 (LWP 11350)):
#0  __clock_nanosleep (clock_id=<optimized out>, flags=1, req=0x7fa2f4f45db0, rem=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x0000000000617160 in ?? ()
#2  0x000000000058ae41 in ?? ()
#3  0x0000000000587b2b in ?? ()
#4  0x0000000000629a8c in ?? ()
#5  0x00007fa2f45906ba in start_thread (arg=0x7fa2f4f46700) at pthread_create.c:333
#6  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fa2f3ee1700 (LWP 11349)):
#0  0x00007fa2f4598827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fa2f45988d4 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007fa2f459897a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000622e06 in mono_sem_wait ()
#5  0x00000000005a5742 in ?? ()
#6  0x0000000000587b2b in ?? ()
#7  0x0000000000629a8c in ?? ()
#8  0x00007fa2f45906ba in start_thread (arg=0x7fa2f3ee1700) at pthread_create.c:333
#9  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fa2f37ff700 (LWP 11348)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fdcdb in ?? ()
#2  0x00007fa2f45906ba in start_thread (arg=0x7fa2f37ff700) at pthread_create.c:333
#3  0x00007fa2f42c641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7fa2f50a5780 (LWP 11347)):
#0  0x00007fa2f4599f7b in __waitpid (pid=11356, stat_loc=0x7fa2f500710c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004a0006 in ?? ()
#2  0x00000000004f390e in ?? ()
#3  0x0000000000426c19 in ?? ()
#4  <signal handler called>
#5  0x00007fa2f4ec773c in elf_machine_rela (skip_ifunc=0, reloc_addr_arg=0x7fa2c0879fe8, version=0x48, sym=0x7fa2c05d2330, reloc=0x7fa2c05e5968, map=0x2dc2750) at ../sysdeps/x86_64/dl-machine.h:301
#6  elf_dynamic_do_Rela (skip_ifunc=0, lazy=<optimized out>, nrelative=<optimized out>, relsize=<optimized out>, reladdr=<optimized out>, map=0x2dc2750) at do-rel.h:137
#7  _dl_relocate_object (scope=<optimized out>, reloc_mode=reloc_mode@entry=1, consider_profiling=<optimized out>, consider_profiling@entry=0) at dl-reloc.c:258
#8  0x00007fa2f4ed0851 in dl_open_worker (a=a@entry=0x7ffc67330ee0) at dl-open.c:435
#9  0x00007fa2f4ecb564 in _dl_catch_error (objname=objname@entry=0x7ffc67330ed0, errstring=errstring@entry=0x7ffc67330ed8, mallocedp=mallocedp@entry=0x7ffc67330ecf, operate=operate@entry=0x7fa2f4ed04d0 <dl_open_worker>, args=args@entry=0x7ffc67330ee0) at dl-error.c:187
#10 0x00007fa2f4ecfda9 in _dl_open (file=0x7fa2e3ffc450 "libXcursor.so.1", mode=-2147483647, caller_dlopen=0x7fa2e3ce1dba, nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x7ffc67331e50) at dl-open.c:660
#11 0x00007fa2f47a6f09 in dlopen_doit (a=a@entry=0x7ffc67331110) at dlopen.c:66
#12 0x00007fa2f4ecb564 in _dl_catch_error (objname=0x28e1a10, errstring=0x28e1a18, mallocedp=0x28e1a08, operate=0x7fa2f47a6eb0 <dlopen_doit>, args=0x7ffc67331110) at dl-error.c:187
#13 0x00007fa2f47a7571 in _dlerror_run (operate=operate@entry=0x7fa2f47a6eb0 <dlopen_doit>, args=args@entry=0x7ffc67331110) at dlerror.c:163
#14 0x00007fa2f47a6fa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#15 0x00007fa2e3ce1dba in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#16 0x00007fa2e3ce22bf in XCreateGlyphCursor () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#17 0x00007fa2e3ce2646 in XCreateFontCursor () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#18 0x00000000400a6e86 in ?? ()
#19 0x00007fa2f3bf8458 in ?? ()
#20 0x00007fa2f3bf88d8 in ?? ()
#21 0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Abandon (core dumped)
```
I hope, this will help you.
Best regards.

**Comment by skillian** [comment]
I'm getting the same behavior and stack trace running Debian Jesse 8.9 on 32-bit x86 running Mono 5.16.0.179 except for the part from gdb.  There, I instead get:

    mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

**Comment by SourMesen** [comment]
One likely reason would be that an incompatible version of the C++ library or the SDL2 library is installed.  Do you get the same crash if you compile the code yourself?

**Comment by SourMesen** [comment]
Closing this for now - it is likely to be a system configuration issue (or an incompatibility between the prebuilt binary and the system it is running on).  Ensuring you have sufficiently recent versions of all requirements (e.g Mono, SDL2, etc.) and compiling from source should solve these kinds of problems in most scenarios.
