### ISSUE TITLE
Libretro core segfaults on OSX

### ISSUE THREAD

**Issue by kivutar** [SourMesen/Mesen#529]
On Ludo:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15197612]

runtime stack:
runtime.throw(0x43f7808, 0x2a)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42f1210, 0xc003869be8, 0xc003869be0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc003869bb8 sp=0xc003869b80 pc=0x400538e
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_set_video_refresh(0x15197600, 0x42f0e10)
	_cgo_gotypes.go:511 +0x41 fp=0xc003869be8 sp=0xc003869bb8 pc=0x410eb41
github.com/libretro/ludo/libretro.(*Core).SetVideoRefresh.func1(0x15197600, 0x42f0e10)
	/Users/kivutar/go/src/github.com/libretro/ludo/libretro/libretro.go:373 +0x8f fp=0xc003869c20 sp=0xc003869be8 pc=0x411176f
github.com/libretro/ludo/libretro.(*Core).SetVideoRefresh(0x4678240, 0xc0000a1330)
	/Users/kivutar/go/src/github.com/libretro/ludo/libretro/libretro.go:373 +0x50 fp=0xc003869c40 sp=0xc003869c20 pc=0x4110380
github.com/libretro/ludo/core.Load(0x7ffeefbff812, 0x1a, 0xc003ec2500, 0x0)
	/Users/kivutar/go/src/github.com/libretro/ludo/core/core.go:56 +0x195 fp=0xc003869eb8 sp=0xc003869c40 pc=0x4177725
main.main()
	/Users/kivutar/go/src/github.com/libretro/ludo/main.go:104 +0x485 fp=0xc003869f98 sp=0xc003869eb8 pc=0x42e20b5
runtime.main()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201 +0x207 fp=0xc003869fe0 sp=0xc003869f98 pc=0x402e217
runtime.goexit()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc003869fe8 sp=0xc003869fe0 pc=0x4058df1
```

On RetroArch:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libretro.RetroArch            	0x000000010f35f60f cocoa_input_state + 109
1   libretro.RetroArch            	0x000000010f3694b2 input_poll + 228
2   libretro.RetroArch            	0x000000010f39ab43 core_run + 148
3   libretro.RetroArch            	0x000000010f39e0c5 runloop_iterate + 5564
4   libretro.RetroArch            	0x000000010f322f18 -[RetroArch_OSX rarch_main] + 61
5   com.apple.Foundation          	0x00007fff529e7abb __NSThreadPerformPerform + 327
6   com.apple.CoreFoundation      	0x00007fff50609155 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
7   com.apple.CoreFoundation      	0x00007fff506090fb __CFRunLoopDoSource0 + 108
8   com.apple.CoreFoundation      	0x00007fff505ecb95 __CFRunLoopDoSources0 + 195
9   com.apple.CoreFoundation      	0x00007fff505ec13e __CFRunLoopRun + 1219
10  com.apple.CoreFoundation      	0x00007fff505eba28 CFRunLoopRunSpecific + 463
11  com.apple.HIToolbox           	0x00007fff4f884b35 RunCurrentEventLoopInMode + 293
12  com.apple.HIToolbox           	0x00007fff4f884774 ReceiveNextEventCommon + 371
13  com.apple.HIToolbox           	0x00007fff4f8845e8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
14  com.apple.AppKit              	0x00007fff4db40eb7 _DPSNextEvent + 997
15  com.apple.AppKit              	0x00007fff4db3fc56 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
16  com.apple.AppKit              	0x00007fff4db39cb9 -[NSApplication run] + 699
17  com.apple.AppKit              	0x00007fff4db293f7 NSApplicationMain + 780
18  libdyld.dylib                 	0x00007fff7d7cd08d start + 1
```

**Comment by SourMesen** [comment]
The macOS version of the core has essentially never been tested/fixed and does not work, afaik.  See #306 for similar problems.
