### ISSUE TITLE
Problem playing Metal Gear: Snake's Revenge NSF file

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#62]
NSF File: https://mega.nz/#!K4JVDDAS!m5T5y2AXnqmVOmlVEvbo1_bV8rz1IXo8CCmGHwLONoI
Dunno where Mesen stores its configuration file, I'd provide a copy of it if I did.

The file plays but the audio is wrong/audio channels are missing. Windows 10 AU Pro x64, Mesen 0.5.3 Beta.

```
---------------------------
Mesen
---------------------------
An unexpected error has occurred.

Error details:
System.ArgumentOutOfRangeException: InvalidArgument=Value of '255' is not valid for 'SelectedIndex'.

Parameter name: SelectedIndex

   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)

   at Mesen.GUI.Controls.ctrlNsfPlayer.UpdateTrackDisplay()

   at Mesen.GUI.Controls.ctrlNsfPlayer.UpdateText()

   at Mesen.GUI.Forms.frmMain.InitializeNsfMode(Boolean updateTextOnly, Boolean gameLoaded)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
---------------------------
OK   
---------------------------
```

**Comment by SourMesen** [comment]
Thanks for the bug report!
This is fixed by 3b2840ef81d22a0a0df9a15c8b58fcdf53bee33f

For your info, all of Mesen's data is saved in My Documents\Mesen - there is a button to open the folder in Options->Preferences

**Comment by Nicholas-Steel** [comment]
Awesome stuff

**Comment by Nicholas-Steel** [comment]
I actually didn't realize this at the time, the NSF plays fine it's just failing to figure out the default track # to begin playback on. Navigate to Track 1 and everything works fine.

I'm aware you're aware of this of course.

**Comment by Nicholas-Steel** [comment]
I can confirm this is fixed. Mesen will now default to Track 1 for the file.

**Comment by SourMesen** [comment]
Thanks for the confirmation!
