### ISSUE TITLE
System.AccessViolationException on close during gameplay

### ISSUE THREAD

**Issue by vrubleg** [SourMesen/Mesen#675]
Mesen v0.9.8, Windows 7 32-bit. I was just playing Super Mario Bros. Then, I've tried to close window of Mesen, and as the result I have this error:

```
---------------------------
Mesen
---------------------------
An unexpected error has occurred.

Error details:
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at Mesen.GUI.InteropEmu.GetScreenSizeWrapper(ConsoleId consoleId, ScreenSize& size, Boolean ignoreScale)
   at Mesen.GUI.Forms.frmMain.SetScaleBasedOnDimensions(Size dimensions, Boolean allowVsDualScreen)
   at Mesen.GUI.Forms.frmMain.frmMain_Resize(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Form.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SetMenu(HandleRef hWnd, HandleRef hMenu)
   at System.Windows.Forms.Form.UpdateMenuHandles(MainMenu menu, Boolean forceRedraw)
   at System.Windows.Forms.Form.UpdateMenuHandles()
   at System.Windows.Forms.Form.set_MainMenuStrip(MenuStrip value)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at Mesen.GUI.Forms.frmMain.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Form.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmSysCommand(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Form.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmNcButtonDown(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Mesen.GUI.Program.Main(String[] args)
---------------------------
OK   
---------------------------
```
Hope, it will be clear from this message what was wrong. I can reproduce it sometimes when I switch to fullscreen mode (F11) and back several times before closing window of Mesen.

**Comment by SourMesen** [comment]
Thanks for the report- this is a rather unexpected error, I wonder what causes it to occur on your system.  Either way, it should be fairly easy to fix with the error message, thanks!

**Comment by SourMesen** [comment]
This should be fixed by 29ef07af09024688e9b74b3de3aa9a760e9d91f9

**Comment by shichongrui** [comment]
I get this error every time I run Mesen.exe via the command line with the --testrunner option. Thanks for the fix. Is there a plan for when the next release will be so I can keep an eye out for the fix?

**Comment by vrubleg** [comment]
@shichongrui you can always download current build on this page:
https://ci.appveyor.com/project/Sour/mesen/build/artifacts

**Comment by vrubleg** [comment]
@SourMesen you might also interested to look into @shichongrui 's issue, probably it is still easy to reproduce.
